<%@ Page Title="" Language="VB" MasterPageFile="~/crms.master" AutoEventWireup="false" CodeFile="BuildLeadList.aspx.vb" Inherits="LeadManagement_BuildLeadList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table>
        <tr>
            <td>List Description:</td>
            <td><asp:TextBox ID="txtDesc" runat="server"></asp:TextBox></td>
        </tr>
    </table>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>
    <table>
        <tr>
            <td colspan = "2">Min. First Name Length:</td>
            <td>
                <asp:DropDownList ID="ddFNameLength" runat="server" AutoPostBack="True">
                </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td colspan = "2">Min. Last Name Length:</td>        
            <td><asp:DropDownList ID="ddLNameLength" runat="server" AutoPostBack="True">
                </asp:DropDownList></td>
        </tr>
        <tr>
            <td colspan = "2">Min. Months Since Last Tour:</td>
            <td><asp:DropDownList ID="ddMonthsOut" runat="server"></asp:DropDownList></td>
        </tr>
        <tr>
            <td colspan = "2">Phone Number Required:</td>
            <td>
                <asp:CheckBox ID="cbPhoneReq" runat="server" AutoPostBack="True" />
            </td>
        </tr>
    </table>
    <asp:Table ID="tblAreaCodes" runat="server" Visible = "false">
    
        <asp:TableRow ID="TableRow1" runat="server">
            <asp:TableCell runat="server">Filter Area Codes:</asp:TableCell>
            <asp:TableCell runat="server"><asp:CheckBox ID="cbFilterAreaCode" runat="server" AutoPostBack="True" /></asp:TableCell>
        </asp:TableRow>
        <asp:TableRow ID="TableRow2" runat="server">
            <asp:TableCell ID="TableCell1" runat="server">Area Codes:</asp:TableCell>
            <asp:TableCell ID="TableCell2" runat="server"><asp:DropDownList ID="ddAreaCodes" runat="server" /><asp:Button ID="btnAddAC" runat="server" Text="Add" /></asp:TableCell>
        </asp:TableRow>
    
    </asp:Table>
    <asp:GridView ID="gvAreaCodes" runat="server" AutoGenerateDeleteButton="True">
    </asp:GridView>
    <table>
        <tr>
            <td colspan = "2">Qualifications:</td>
        </tr>
        <tr>
            <td>Field:</td>
            <td>
                <asp:DropDownList ID="ddQualField" runat="server" AutoPostBack="True">
                </asp:DropDownList>
            </td>
            <td>Value:</td>
            <td>
                <asp:DropDownList ID="ddQualValue" runat="server">
                </asp:DropDownList>
            </td>
            <td>
                <asp:Button ID="Button1" runat="server" Text="Add" /></td>
        </tr>
    </table>
    <asp:GridView ID="gvQualifications" runat="server" AutoGenerateDeleteButton="True">
    </asp:GridView>
    <table>
        <tr>
            <td colspan = "2">Exclusions:</td>
        </tr>
                <tr>
            <td>Field:</td>
            <td>
                <asp:DropDownList ID="ddExcludeField" runat="server" AutoPostBack="True">
                </asp:DropDownList>
            </td>
            <td>Value:</td>
            <td>
                <asp:DropDownList ID="ddExcludeValue" runat="server">
                </asp:DropDownList>
            </td>
            <td>
                <asp:Button ID="Button2" runat="server" Text="Add" /></td>
        </tr>
    </table>
    <asp:GridView ID="gvExclusions" runat="server" AutoGenerateDeleteButton="True">
    </asp:GridView>
    <table>
        <tr>
            <td>New Leads:</td>
            <td><asp:TextBox ID="txtNewLeadsQty" runat="server">0</asp:TextBox>    <asp:Label ID="lblNewQtyAvail"
                    runat="server" Text="0"></asp:Label> Available</td>
        </tr>
        <tr>
            <td>Recycled Leads: </td>
            <td><asp:TextBox ID="txtOldLeadsQty" runat="server">0</asp:TextBox>    <asp:Label ID="lblOldQtyAvail"
                    runat="server" Text="0"></asp:Label> Available</td>
        </tr>
        <tr>
            <td>Vendor:</td>
            <td>
                <asp:DropDownList ID="ddVendors" runat="server">
                </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Button ID="btnSave" runat="server" Text="Build List" />
                <asp:Button ID="btnCounts" runat="server" Text="Get Counts" />
            </td>
        </tr>
    </table>

        <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        <br />
        <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
    </ContentTemplate>
    </asp:UpdatePanel>

</asp:Content>

