vti_encoding:SR|utf8-nl
vti_author:SR|KCP\\RHill
vti_modifiedby:SR|KCP\\RHill
vti_timelastmodified:TR|08 Apr 2012 06:27:15 -0000
vti_timecreated:TR|08 Apr 2012 04:39:28 -0000
vti_lineageid:SR|{695C3DBF-6542-4B26-9A87-BF2CC99B92A5}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|08 Apr 2012 04:39:28 -0000
vti_cacheddtm:TX|08 Apr 2012 06:27:15 -0000
vti_filesize:IR|198
