<%@ Page Title="" Language="VB" MasterPageFile="~/crms.master" AutoEventWireup="false" CodeFile="BulkBankWizard.aspx.vb" Inherits="PropertyManagement_BulkBankWizard" %>
<%@ Register src="~/controls/Select_Item.ascx" tagname="Select_Item" tagprefix="uc1" %>
<%@ Register src="~/controls/DateField.ascx" tagname="DateField" tagprefix="uc2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<table>
    <tr>
        <td># of Usages:</td>
        <td><asp:TextBox runat="server" id = "txtNumUsages"></asp:TextBox></td>
    </tr>
    <tr>
        <td>Usage Year:</td>
        <td><asp:DropDownList runat="server" id = "ddYear"></asp:DropDownList></td>
    </tr>
    <tr>
        <td>Start Date:</td>
        <td><uc2:DateField ID="dteStartDate" runat="server" /></td>
    </tr>
    <tr>
        <td>Nights:</td>
        <td><asp:DropDownList runat="server" id = "ddNights"></asp:DropDownList></td>
    </tr>
    <tr>
        <td>Exchange Company:</td>
        <td><asp:DropDownList runat="server" id = "ddExchCompany"></asp:DropDownList></td>
    </tr>
    <tr>
        <td>Unit Type:</td>
        <td><uc1:Select_Item ID="siUnitType" runat="server" /></td>
    </tr>
    <tr>
        <td>Bedrooms:</td>
        <td><asp:DropDownList runat="server" id = "ddBedRooms"></asp:DropDownList></td>
    </tr>
    <tr>
        <td>Check-In Day:</td>
        <td><uc1:Select_Item ID="siRoomSubType" runat="server" /></td>
    </tr>
    <tr>
        <td><asp:Button runat="server" Text="Add Item" onclick="Unnamed1_Click"></asp:Button></td>
        <td><asp:Button runat="server" id = "btnSubmit" Text="Submit Usages"></asp:Button></td>
    </tr>
        
</table>
<asp:GridView runat="server" id = "gvBulkBank" AutoGenerateDeleteButton="True" EnableModelValidation="True" onRowDataBound = "gvBulkBank_RowDataBound">

</asp:GridView>
<asp:Label runat="server" id = "lblErr"></asp:Label>

</asp:Content>

