<%@ Page Language="VB" MasterPageFile="~/crms.master" AutoEventWireup="false" CodeFile="EditRequest.aspx.vb" Inherits="Maintenance_EditRequest" Title="Edit Maintenance Request"%>

<%@ Register src="../controls/DateField.ascx" tagname="DateField" tagprefix="uc1" %>
<%@ Register src="../controls/Select_Item.ascx" tagname="Select_Item" tagprefix="uc2" %>



<%@ Register src="../controls/Notes.ascx" tagname="Notes" tagprefix="uc3" %>



<%@ Register src="../controls/Events.ascx" tagname="Events" tagprefix="uc4" %>



<asp:content ID="Content1" contentplaceholderid="head" runat="server">
    <script language=javascript type ="text/javascript">
    function Refresh_Parts(transType) {
        if (transType == 'addPart') {
            __doPostBack('ctl00$ContentPlaceHolder1$Part_Link', '');
        }
        else if (transType == 'move') {
            __doPostBack('ctl00$ContentPlaceHolder1$PartMove_Link', '');
        }
        else if (transType == 'loan') {
            __doPostBack('ctl00$ContentPlaceHolder1$PartLoan_Link', '');
        }
    }
    </script>
</asp:content>
<asp:content ID="Content2" contentplaceholderid="ContentPlaceHolder1" runat="server">
    <ul id="menu">
        <li <%if  MultiView1.ActiveViewIndex = 0 then: response.write ("class=""current"""):end if %>><asp:LinkButton ID="Request_Link" runat="server">Maint. Request</asp:LinkButton></li>
        <li <%if  MultiView1.ActiveViewIndex = 1 then: response.write ("class=""current"""):end if %>><asp:LinkButton ID="Part_Link" runat="server">Parts</asp:LinkButton></li>
        <li <%if  MultiView1.ActiveViewIndex = 2 then: response.write ("class=""current"""):end if %>><asp:LinkButton ID="PartMove_Link" runat="server">Part Moves</asp:LinkButton></li>
        <li <%if  MultiView1.ActiveViewIndex = 3 then: response.write ("class=""current"""):end if %>><asp:LinkButton ID="PartLoan_Link" runat="server">Parts Loaned</asp:LinkButton></li>
        <li <%if  MultiView1.ActiveViewIndex = 4 then: response.write ("class=""current"""):end if %>><asp:LinkButton ID="Notes_Link" runat="server">Notes</asp:LinkButton></li>
        <li <%if  MultiView1.ActiveViewIndex = 5 then: response.write ("class=""current"""):end if %>><asp:LinkButton ID="Events_Link" runat="server">Events</asp:LinkButton></li>

    </ul>

        <asp:MultiView ID="MultiView1" runat="server">
                <asp:View ID="Request_View" runat="server">
                    <table>
                        <tr>
                            <td>RequestID:</td>
                            <td><asp:TextBox ID="txtRequestID" runat="server" ReadOnly></asp:TextBox></td>
                            <td>Date:</td>
                            <td><asp:TextBox ID="txtDate" runat="server" readonly></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Generated By:</td>
                            <td><uc2:Select_Item ID="siLocation" runat="server" /></td>
                            <!--<td>Room Number:</td>
                            <td><asp:DropDownList runat="server" id="ddRoom"></asp:DropDownList></td>-->
                        </tr>
                        <tr>
                            <td>Problem Location:</td>
                            <td><asp:DropDownList runat="server" id = "ddKF" AutoPostBack ="true"></asp:DropDownList></td>
                            <td>
                                <asp:Label ID="lblKF" runat="server" Text="Label"></asp:Label></td>
                            <td>
                                <asp:DropDownList ID="ddKV" runat="server"></asp:DropDownList></td>
                        </tr>
                        <tr>
                            <td>Assigned To:</td>
                            <td><asp:DropDownList runat="server" id="ddAssignedTo"></asp:DropDownList></td>
                            <td>Status:</td>
                            <td><uc2:Select_Item ID="siStatus" runat="server" /></td>
                        </tr>
                        <tr>
                            <td>Category:</td>
                            <td><asp:DropDownList runat="server" id = "ddCategory"></asp:DropDownList></td>
                            <td>Issue:</td>
                            <td><uc2:Select_Item ID="siIssue" runat="server" /></td>
                        </tr>
                        <tr>
                            <td>Start Date:</td>
                            <td><uc1:DateField ID="txtSDate" runat="server"></uc1:DateField></td>
                            <td>StartTime:</td>
                            <td><asp:TextBox ID="txtSTime" runat="server"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>End Date:</td>
                            <td><uc1:DateField ID="txtEDate" runat="server" ReadOnly></uc1:DateField></td>
                            <td>End Time:</td>
                            <td><asp:TextBox ID="txtETime" runat="server"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Subject:</td>
                            <td><asp:TextBox ID="txtSubject" runat="server"></asp:TextBox></td>
                            <td>Priority</td>
                            <td><asp:DropDownList ID="ddPriority" runat="server">
                                <asp:ListItem>1</asp:ListItem>
                                <asp:ListItem>2</asp:ListItem>
                                <asp:ListItem Selected="True">3</asp:ListItem>
                                </asp:DropDownList></td>
                        </tr>
                        <tr>
                            <td>Description:</td>
                        </tr>
                        <tr>
                            <td colspan = '3'>
                                <asp:TextBox ID="txtDescription" runat="server"
                                    TextMode="MultiLine" Height="50px" Width="365px"></asp:TextBox>
                            </td>
                            <td><asp:Button runat="server" Text="Print" id="btnPrint"></asp:Button></td>
                        </tr>
                    </table>
                    <asp:Button ID="btnSave" runat="server" Text="Save" />
                    <asp:Label runat="server" Text="" id = "lblMessage"></asp:Label>
                </asp:View>
                <asp:View runat="server" id = "Parts_View">
                          <asp:GridView id = "gvParts" runat="server" EnableModelValidation="True" Autogeneratecolumns = "False" emptyDataText = "No Records" OnRowDataBound = "gvParts_RowDataBound">
                            <Columns>
                                <asp:BoundField HeaderText="ID" DataField="Part2RequestID"></asp:BoundField>
                                <asp:BoundField HeaderText="Item Number" DataField="ItemNumber"></asp:BoundField>
                                <asp:BoundField HeaderText="Description" DataField="Description"></asp:BoundField>
                                <asp:BoundField HeaderText="Qty" DataField="Qty"></asp:BoundField>
                                <asp:BoundField HeaderText="Status" DataField="Status"></asp:BoundField>
                                <asp:BoundField HeaderText="PRID" DataField="PRID"></asp:BoundField>
                                <asp:BoundField HeaderText="Remove" DataField="Remove"></asp:BoundField>
                                <asp:ButtonField CommandName="RemovePart" Text="Remove"></asp:ButtonField>
                                <asp:BoundField HeaderText="Install" DataField="Install"></asp:BoundField>
                                <asp:ButtonField CommandName="Install" Text="Install"></asp:ButtonField>
                            </Columns>
                        </asp:GridView>
                            <asp:Button runat="server" Text="Add Part" onclick="Unnamed1_Click"></asp:Button>
                            <asp:Label runat="server" id = "lblErr" Text=""></asp:Label>
                </asp:View>
                <asp:View runat="server" id = "PartsMove_View">
                    <asp:GridView ID="gvPartsMoved" runat="server" Autogeneratecolumns="False" emptyDataText="No Records" EnableModelValidation="True" OnRowDataBound="gvPartsMoved_RowDataBound">
                        <Columns>
                            <asp:BoundField DataField="RequestPartMoveID" HeaderText="ID"></asp:BoundField>
                            <asp:BoundField DataField="ItemNumber" HeaderText="Item Number"></asp:BoundField>
                            <asp:BoundField DataField="Description" HeaderText="Description"></asp:BoundField>
                            <asp:BoundField DataField="Qty" HeaderText="Qty"></asp:BoundField>
                            <asp:BoundField DataField="MovedFrom" HeaderText = "Moved From"></asp:BoundField>
                            <asp:BoundField DataField="Status" HeaderText="Status"></asp:BoundField>
                            <asp:BoundField DataField="Remove" HeaderText="Remove"></asp:BoundField>
                            <asp:ButtonField CommandName="Remove" Text="Remove"></asp:ButtonField>
                            <asp:BoundField DataField="Install" HeaderText="Install"></asp:BoundField>
                            <asp:ButtonField CommandName="Install" Text="Install"></asp:ButtonField>
                        </Columns>
                    </asp:GridView>
                    <asp:Button runat="server" Text="Add Part Move" onclick="Unnamed2_Click"></asp:Button>
                </asp:View>
                <asp:View runat="server" id = "PartsLoan_View">
                <asp:GridView ID="gvPartsLoaned" runat="server" Autogeneratecolumns="False" emptyDataText="No Records" EnableModelValidation="True" OnRowDataBound="gvPartsLoaned_RowDataBound">
                        <Columns>
                            <asp:BoundField DataField="RequestPartLoanID" HeaderText="ID"></asp:BoundField>
                            <asp:BoundField DataField="ItemNumber" HeaderText="Item Number"></asp:BoundField>
                            <asp:BoundField DataField="Description" HeaderText="Description"></asp:BoundField>
                            <asp:BoundField DataField="Qty" HeaderText="Qty"></asp:BoundField>
                            <asp:BoundField DataField="ReservationID" HeaderText = "Reservation"></asp:BoundField>
                            <asp:BoundField DataField="MovedFrom" HeaderText = "Room"></asp:BoundField>
                            <asp:BoundField DataField="DatePickedUp" HeaderText = "Return Date"></asp:BoundField>
                            <asp:BoundField DataField="Status" HeaderText="Status"></asp:BoundField>
                            <asp:BoundField DataField="Return" HeaderText="Return"></asp:BoundField>
                            <asp:ButtonField CommandName="Return" Text="Return"></asp:ButtonField>
                        </Columns>
                    </asp:GridView>
                    <asp:Button runat="server" Text="Add Part Loan" onclick="Unnamed3_Click"></asp:Button>
                </asp:View>
                <asp:View ID="Notes_View" runat="server">
                     <uc3:Notes ID="Notes1" runat="server" KeyField = "RequestID"/>
                </asp:View>
                <asp:View ID="Events_View" runat="server">
                    <uc4:Events ID="ucEvents" runat="server" />
                </asp:View>
       
            </asp:MultiView>
        
</asp:content>
