<%@ Page Title="" Language="VB" MasterPageFile="~/crms.master" AutoEventWireup="false" CodeFile="FDWorkOrderEntry.aspx.vb" Inherits="Maintenance_FDWorkOrderEntry" %>
<%@ Register src="../controls/Select_Item.ascx" tagname="Select_Item" tagprefix="uc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<script type="text/javascript">
function add_Item(a, b, c)
{

	__doPostBack('ctl00$ContentPlaceHolder1$LinkButton1', '');
}

function remove_Row() {
    var tbl = document.getElementById("ctl00_ContentPlaceHolder1_Table1");
    var del = false;
    if (tbl.rows.length < 2) {
        alert('No rows Available for Removal.');
    }
    else {
        for (i = 1; i < tbl.rows.length; i++) {
            if (tbl.rows(i).bgColor == "#81e2e2") {
                tbl.deleteRow(i);
                del = true;
            }
        }

        if (del == false) {
            alert('Please Select a Row to Remove.');
        }
    }
}
function popWindow() {

    modal.mwindow.open('FDWorkOrderItem.aspx', 'win01', 350, 350);
}
function highlight(row)
{
    var tbl = document.getElementById("ctl00_ContentPlaceHolder1_Table1");
	for (i=1;i<tbl.rows.length;i++)
	{
		if (tbl.rows(i).bgColor == "#81e2e2")
		{	
			tbl.rows(i).bgColor = "";
		}

	}
	row.bgColor = "#81E2E2";
}
</script>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<table>
    <tr>
        <td>Problem Location: </td>
        <td><uc1:Select_Item ID="siProblemArea" runat="server" /></td>
        <td>Room Number: </td>
        <td><asp:DropDownList runat="server" id = "ddRooms"></asp:DropDownList></td>
    </tr>
</table> 

<asp:GridView runat="server" id = "gvItems" EnableModelValidation="True" Autogeneratecolumns = "False" AutoGenerateDeleteButton="True">
    <Columns>
    <asp:BoundField HeaderText="Category" DataField="Category"></asp:BoundField>
    <asp:BoundField HeaderText="Issue" DataField="Issue"></asp:BoundField>
    <asp:BoundField HeaderText="Description" DataField="Description"></asp:BoundField>
    </Columns>
</asp:GridView>
<input id = "button2" type = "button" value="Add item" onclick="popWindow();"></asp:Button>
<br />
<asp:Button runat="server" Text="Submit" onclick="Unnamed1_Click1"></asp:Button>
    <asp:LinkButton ID="LinkButton1" runat="server"></asp:LinkButton>
</asp:Content>

