<%@ Page Title="" Language="VB" MasterPageFile="~/crms.master" AutoEventWireup="false" CodeFile="ExitTourWizard.aspx.vb" Inherits="wizards_ExitTourWizard" %>
<%@ Register src="../controls/Select_Item.ascx" tagname="Select_Item" tagprefix="uc1" %>
<%@ Register src="../controls/DateField.ascx" tagname="DateField" tagprefix="uc2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<asp:MultiView runat="server" id = "MultiView1">
<asp:View runat="server" id = "View1">
<table>
<tr>
    <td>TourID:</td>
    <td><%=request("TourID") %></td>
</tr>
<tr>
    <td>Current Status:</td>
    <td><asp:Label runat="server" id = "lbltStatus"></asp:Label></td>
</tr>
<tr>
    <td>New Tour Status:</td>
    <td>
        <uc1:Select_Item ID="siTourStatus" runat="server" />
    </td>
</tr>
<tr>
    <td>Select TO:</td>
    <td>
        <asp:DropDownList runat="server" id = "ddTO"></asp:DropDownList>
    </td>
</tr>
<tr>
    <td colspan = '2'>Was an Exit Tour Completed?</td>
</tr>
<tr>
    <td><asp:RadioButtonList runat="server" RepeatDirection="Horizontal" 
            TextAlign="Left" onselectedindexchanged="exitTourChk_SelectedIndexChanged" 
            id = "exitTourChk" AutoPostBack="True">
        <asp:ListItem>Yes:</asp:ListItem><asp:ListItem>No:</asp:ListItem>
        </asp:RadioButtonList></td>
</tr>
</table>
    <asp:label id = "lblExitReps" visible = "false" runat="server">Assign Sales Rep:</asp:label><asp:DropDownList runat="server" id = "ddExitReps" visible = "false"></asp:DropDownList>
<br />
<br />
Check the Premiums that were Issued:
<asp:GridView runat="server" id = "gvPremiums" EnableModelValidation="True">
    <Columns>
        <asp:TemplateField HeaderText="Select">
            <ItemTemplate>
                <asp:checkbox ID="PremSelect" runat = "server" />
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
    </asp:GridView>
    <br />
    <table>
    <tr>
    <td colspan = "2">

            Did the Customer Purchase?
            </td>

        </tr>
    <tr>
    <td colspan = "2">
<asp:RadioButtonList runat="server" RepeatDirection="Horizontal" TextAlign="Left" 
        id = "purchaseChk" AutoPostBack="True" onselectedindexchanged="purchaseChk_SelectedIndexChanged">
    <asp:ListItem>Deed Purchase:</asp:ListItem>
    <asp:ListItem>No:</asp:ListItem>
    </asp:RadioButtonList>    
    </td>
    </tr></table>

         <asp:Label runat="server" visible = "false" id = "purchaselbl">Contract Number: </asp:Label>   

         <asp:TextBox runat="server" id = "contractTxt" visible = "false"></asp:TextBox>    


<br />
<!--Remove VC option per workorder 40153 10/28/13
Is the Customer Going to Tour with Vacation Club?
<br />
<asp:RadioButtonList runat="server" RepeatDirection="Horizontal" TextAlign="Left" id = "vClubChk">
    <asp:ListItem>Yes:
    </asp:ListItem>
    <asp:ListItem>No:
    </asp:ListItem>
    </asp:RadioButtonList> -->

<asp:Button runat="server" Text="Check Out" onclick="Unnamed1_Click" 
        onclientclick="this.disabled=true;" ID = "btnCheckOut" 
        UseSubmitBehavior="False"></asp:Button>
<asp:Label runat="server" id = "lblErr"></asp:Label><asp:HiddenField runat="server" id = "hfTourID"></asp:HiddenField>
</asp:View>
<asp:View runat="server" id = "View2">
    <table>
        <tr>
            <td>TourDate:</td>
            <td colspan = '2'><uc2:DateField ID="dteTourDate" runat="server" /></td>
        </tr>
        <tr>
            <td>Tour Time:</td>
            <td><uc1:Select_Item ID="siTourTime" runat="server" /></td>
        </tr>
        <tr>
            <td>Solicitor:</td>
            <td><asp:DropDownList runat="server" id = "ddExit"></asp:DropDownList></td>
        </tr>
        <tr>
            <td>Premium:</td>
            <td><asp:DropDownList runat="server" id = "ddPremiums"></asp:DropDownList></td>
            <td>Qty:</td>
            <td><asp:DropDownList runat="server" id = "ddQty"></asp:DropDownList></td>
            <td>Amount:</td>
            <td><asp:TextBox runat="server" id = "txtAmount" Width="58px"></asp:TextBox></td>
            <td><asp:Button runat="server" Text="Add Premium" onclick="Unnamed2_Click"></asp:Button></td>
        </tr>
        <tr>
            <td><asp:Button runat="server" Text="Submit Tour" onclick="Unnamed3_Click"></asp:Button></td>
        </tr>
    </table>
    <asp:GridView runat="server" id = "gvVCPremiums" 
        AutoGenerateDeleteButton="True" EnableModelValidation="True" AutoGenerateColumns = "False" onRowDataBound = "gvVCPremiums_RowDataBound">
            <Columns>
                <asp:BoundField DataField="PremiumID" HeaderText="PremiumID"></asp:BoundField>
                <asp:BoundField DataField="PremiumName" HeaderText = "Premium"></asp:BoundField>
                <asp:BoundField DataField="Qty" HeaderText = "Qty"></asp:BoundField>
                <asp:BoundField DataField="Amount" HeaderText = "Amount"></asp:BoundField>
            </Columns>
        
    </asp:GridView>
        <asp:Label runat="server" id = "lblErr2"></asp:Label>
</asp:View>
<asp:View runat="server" id = "viewDeny">ACCESS DENIED</asp:View>
</asp:MultiView>
</asp:Content>

