<%@ Page Title="" Language="VB" MasterPageFile="~/crms.master" AutoEventWireup="false" CodeFile="RateTableHolidays.aspx.vb" Inherits="setup_RateTableHolidays" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<script language=javascript type ="text/javascript">
    function Refresh_Dates() {
        __doPostBack('ctl00$ContentPlaceHolder1$btnList', '');
    }
</script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:Button ID="btnList" runat="server" Text="List" />
    <asp:Button ID="btnAdd" runat="server" Text="Add" />
    <asp:GridView ID="gvHolidays" runat="server" EmptyDataText ="No Records" AutoGenerateDeleteButton ="true">
    </asp:GridView>
</asp:Content>

