vti_encoding:SR|utf8-nl
vti_author:SR|KCP\\MBenton
vti_modifiedby:SR|KCP\\MBenton
vti_timelastmodified:TR|22 Aug 2011 15:42:25 -0000
vti_timecreated:TR|22 Aug 2011 15:15:05 -0000
vti_lineageid:SR|{452DE796-D291-4463-AA22-434B012D16B8}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|22 Aug 2011 15:34:21 -0000
vti_cacheddtm:TX|22 Aug 2011 15:42:25 -0000
vti_filesize:IR|205
